#24: Add autoInferenceColumnNames property
exasol/edml-java pull request #25
Opened 2024-06-12 13:15 UTC by kaklakariada

Closes #24

2024-06-12 17:32 UTC, tomuben commented on src/main/java/com/exasol/adapter/document/edml/deserializer/EdmlDeserializer.java
> +        final String columnNameMapping = json.getString(AUTO_INFERENCE_COLUMN_NAMES, null);
```suggestion
        final String autoInferenceColumnNames = json.getString(AUTO_INFERENCE_COLUMN_NAMES, null);
```

2024-06-12 17:33 UTC, tomuben commented on src/main/java/com/exasol/adapter/document/edml/deserializer/EdmlDeserializer.java
> +            builder.autoInferenceColumnNames(ColumnNameMapping.valueOf(columnNameMapping));
```suggestion
            if (autoInferenceColumnNames != null) {
                throw new IllegalArgumentException(ExaError.messageBuilder("E-EDML-105")
                        .message("Parameter auto inference column names is not allowed when mapping is present.")
                        .mitigation("Remove property {{auto inference property}}.", AUTO_INFERENCE_COLUMN_NAMES)
                        .toString());
            }
        }
        if (autoInferenceColumnNames != null) {
            builder.autoInferenceColumnNames(ColumnNameMapping.valueOf(autoInferenceColumnNames));
```

2024-06-12 18:38 UTC, tomuben submitted a review, later dismissed

2024-06-13 09:01 UTC, ckunki requested changes

2024-06-13 09:01 UTC, ckunki commented on .gitattributes
> +pk_generated_parent.pom                        linguist-generated=true
Do we want to stick to `linguist-generated=true` or do we prefer the shorter `linguist-generated` ?

2024-06-13 09:01 UTC, ckunki commented on doc/changes/changes_2.1.0.md
> +This release adds property `autoInferenceColumnNames` to the EDML definition. This allows users to configure how virtual schemas convert column names from the source to Exasol column names when using
Please add a reference or copy the description about the supported values for this property.
Please specify where to find the property (maybe with a link or reference?)
See file edml-2.1.0.json: 

```json
  "CONVERT_TO_UPPER_SNAKE_CASE",
                "KEEP_SOURCE"
```

2024-06-13 09:01 UTC, ckunki commented on src/main/java/com/exasol/adapter/document/edml/ColumnNameMapping.java
> +    KEEP_SOURCE;
```suggestion
    KEEP_ORIGINAL_NAME;
```

2024-06-13 09:01 UTC, ckunki commented on src/main/java/com/exasol/adapter/document/edml/deserializer/EdmlDeserializer.java
> +            builder.autoInferenceColumnNames(ColumnNameMapping.valueOf(columnNameMapping));
I suggest "Property"

2024-06-13 12:19 UTC, ckunki approved these changes

2024-06-13 12:25 UTC, merged